### ISSUE TITLE
meta dependence

### ISSUE THREAD

**Issue by henda52** [kylehamilton/MAVIS#18]
When I installed and ran MAVIS I got an error message:
> library(shiny)
> library(MAVIS)
> startmavis()

Listening on http://127.0.0.1:7319
Warning: Error in library: there is no package called ‘meta’
Stack trace (innermost first):
    42: library
     2: shiny::runApp
     1: startmavis
Error : there is no package called ‘meta’

It is probably some issue with the dependencies of packages because when I manually installed meta package it worked fine again.

**Comment by kylehamilton** [comment]
Opss, I wrote this down as a problem and I forgot about it! I pushed a fix to the repo so all should work now. Thanks for catching this!
