### ISSUE TITLE
Doesn't show all the results from Meta-analysis

### ISSUE THREAD

**Issue by FranMarquesOrtega** [kylehamilton/MAVIS#24]
The following data does not generate a Fixed-Effect model forest plot despite it assumes homogeneity. 
Study	N1	N2	d
Day (2013)	148	148	0.13
Findik (2012)	60	57	0.2
Wassenberg  (2010)	42	84	0.01
Lupion (2015)	72	72	0.35
It uses Effect Size d. 
Thank's for the software!

**Comment by kylehamilton** [comment]
Sorry for the delay in getting back to you. I donated bone marrow over the Christmas holiday so I've been taking it easy for the last couple of weeks. The results are the same for both random and fixed effect models.  

**Random Effects**

![image](https://user-images.githubusercontent.com/2274317/51097871-59b61700-177c-11e9-81b0-bf3db7112cb7.png)

**Fixed Effects**

![image](https://user-images.githubusercontent.com/2274317/51097879-6470ac00-177c-11e9-98a1-0ebe9327b131.png)

**Comment by FranMarquesOrtega** [comment]
Thank you very much! It is also great to hear you are concerned about the
need for an extended marrow bone pool. Take your time to rest!

El dl., 14 gen. 2019 6.44, W. Kyle Hamilton <notifications@github.com> va
escriure:
